### PR TITLE
Add wildcard notes

### PR DESCRIPTION
**Pull request by hoani**
Add wildcard notes.

Relates to:
https://github.com/cennznet/cennznut-rs/issues/28
https://github.com/cennznet/cennznut-rs/issues/29

### CODE REVIEW

**Review by wilfred-centrality — APPROVED** [review]
This is great. Approved.

**Comment by jordy25519** [comment]
Nice and clear 👍 

These are the permutations:

| Module | Method | Allows                                 |
|--------|--------|----------------------------------------|
| *      | *      | All modules, All methods               |
| *      | [M]    | All modules, Specific method(s)        |
| [M]    | *      | Specific module(s), All methods        |
| [M]    | [M]    | Specific module(s), Specific method(s) |

I think the `* [M]` case is a little funky, it means we allow a certain method name on any module. 
Maybe we should disallow this case? as semantically it ~doesn't make much sense~ is wierd

**Comment by wilfred-centrality** [comment]
I'm happy to disallow it if you feel it's an improvement. I don't have a strong opinion here.

Can I just ask if we are using a permission tree:
```
- m1
    - f1
    - f2
- m2
    - f3
```

Or a lists approach:
```
- m1
- m2
- f1
- f2
- f3
```
```
m = module
f = method
```

**Comment by cowboy-bebug** [comment]
yep we are using the nested tree structure (not flat)
```rust
pub struct Module {
    pub name: String,
    pub block_cooldown: Option<u32>,
    pub methods: Vec<(String, Method)>,  // <- methods for a module
}
```

**Comment by wilfred-centrality** [comment]
Sweet, then I'm happy

**Review by jordy25519 — APPROVED** [review]
`*` module + specific method still feels like a loose end but this is good for now 😄

**Pull request merged**
